# .goreleaser.yaml

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - id: certbox_proxy
    env:
      - CGO_ENABLED=0
#    main: .
    binary: certbox_proxy
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
